version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
     - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  order:
    build: ../microservice-kafka/microservice-kafka-order
    links:
     - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
  shipping:
    build: ../microservice-kafka/microservice-kafka-shipping
    links:
     - kafka
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
  invoicing:
    build: ../microservice-kafka/microservice-kafka-invoicing
    links:
     - kafka
    ports:
      - "8082:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

