version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
  apache:
    build: apache
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
  order:
    build: ../microservice-kafka/microservice-kafka-order
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
  shipping:
    build: ../microservice-kafka/microservice-kafka-shipping
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
  invoicing:
    build: ../microservice-kafka/microservice-kafka-invoicing
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

